apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: anish171/chatapp-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://root:root@mongo-service.chat-app.svc.cluster.local:27017/chatapp?authSource=admin"
        - name: PORT
          value: "5001"